import { toMarkdown } from "../content/snapshot-builder.js";
const $=id=>document.getElementById(id); let tabId=Number(new URLSearchParams(location.search).get("tabId"))||null, snapshots=[];
async function loadTargets(){const old=$("target");const tabs=await chrome.tabs.query({});const usable=tabs.filter(t=>/^https?:/i.test(t.url||""));const select=old||document.createElement("select");select.id="target";select.title="Choose capture target";select.setAttribute("aria-label","Capture target");select.style.cssText="max-width:190px;margin:0 0 12px auto;display:block;overflow:hidden;text-overflow:ellipsis";select.replaceChildren();for(const tab of usable){const option=document.createElement("option");option.value=tab.id;option.textContent=`${tab.title||tab.url} · ${new URL(tab.url).hostname}`;option.selected=tab.id===tabId;select.append(option);}if(!old){select.addEventListener("change",async()=>{tabId=Number(select.value);await load();});$("capture").closest(".capture-row").before(select);}}
chrome.runtime.onMessage.addListener(m=>{if(m.type==="TABS_CHANGED")loadTargets();});
async function load(){if(!tabId){const [tab]=await chrome.tabs.query({active:true,currentWindow:true});tabId=tab?.id;} const data=await chrome.storage.local.get([`snapshots:${tabId}`,"lastSnapshots","lastSnapshotUrl"]); snapshots=data[`snapshots:${tabId}`]||data.lastSnapshots||[]; render();}
function current(){return snapshots.map(toMarkdown).join("\n\n---\n\n")}
function exportSnapshots(){return snapshots.map(({screenshot,...snapshot})=>snapshot);}
function render(){const json=JSON.stringify(exportSnapshots(),null,2);const latest=snapshots.at(-1);$("preview").value=$("format").value==="json"?json:current();$("meta").textContent=snapshots.length?`${snapshots.length} capture${snapshots.length>1?"s":""} · ${latest.metadata.title||"Untitled"}`:"No capture yet";$("shot").style.display="flex";if(latest?.screenshot){$("screenshot").style.display="block";$("emptyShot").style.display="none";$("screenshot").src=latest.screenshot;}else{$("screenshot").style.display="none";$("emptyShot").style.display="flex";}}
function filename(ext){const latest=snapshots.at(-1);const u=latest?.metadata?.url||"page";const host=new URL(u).hostname.replace(/^www\./,"")||"page";const title=(latest?.metadata?.title||"ui").replace(/[^a-z0-9]+/gi,"-").replace(/^-|-$/g,"").slice(0,45)||"ui";return `dom2ai-${host}-${title}-state-${latest?.sequence||1}.${ext}`;}
$("format").addEventListener("change",render); $("capture").addEventListener("click",async()=>{const b=$("capture"),old=b.innerHTML;b.innerHTML="<span>…</span> Capturing";b.disabled=true;try{await chrome.tabs.sendMessage(tabId,{type:"CAPTURE"});await new Promise(r=>setTimeout(r,800));await load();}catch{$("meta").textContent="Reload the source tab, then capture again";}finally{b.innerHTML=old;b.disabled=false;}}); $("clear").addEventListener("click",async()=>{snapshots=[];await chrome.storage.local.remove([`snapshots:${tabId}`,"lastSnapshots","lastSnapshotUrl"]);chrome.tabs.sendMessage(tabId,{type:"CLEAR"}).catch(()=>{});render()}); const flash=async(button,action)=>{const old=button.innerHTML;try{await action();button.innerHTML="✓";button.title="Copied";setTimeout(()=>{button.innerHTML=old;button.title=button.getAttribute("aria-label")||"Copy"},1400);}catch{}}; $("copy").addEventListener("click",()=>flash($("copy"),()=>navigator.clipboard.writeText($("preview").value))); $("download").addEventListener("click",()=>{const ext=$("format").value==="json"?"json":"md", mime=ext==="json"?"application/json":"text/markdown", blob=new Blob([$("preview").value],{type:mime}), url=URL.createObjectURL(blob);chrome.downloads.download({url,filename:filename(ext),saveAs:true})}); $("copyImage").addEventListener("click",()=>flash($("copyImage"),async()=>{const latest=snapshots.at(-1);if(!latest?.screenshot)throw new Error("No screenshot");const blob=await (await fetch(latest.screenshot)).blob();await navigator.clipboard.write([new ClipboardItem({[blob.type]:blob})]);})); $("downloadImage").addEventListener("click",()=>{const latest=snapshots.at(-1);if(latest?.screenshot)chrome.downloads.download({url:latest.screenshot,filename:filename("png"),saveAs:true});}); loadTargets(); load();
const cap=$("capture");const freshCap=cap.cloneNode(true);cap.replaceWith(freshCap);freshCap.addEventListener("click",async()=>{const b=freshCap,old=b.innerHTML;b.innerHTML="<span>…</span> Capturing";b.disabled=true;try{const popup=await chrome.windows.getCurrent();const result=await chrome.runtime.sendMessage({type:"CAPTURE_TARGET",tabId,popupWindowId:popup.id});if(!result?.ok)throw new Error(result?.error||"Capture failed");await load();}catch{$("meta").textContent="Unable to capture this target";}finally{b.innerHTML=old;b.disabled=false;}});
$("enhance")?.addEventListener("click",async()=>{if(!snapshots.length)return;const key=prompt("Paste your Gemini API key. It is stored only in this browser.");if(!key)return;const button=$("enhance"),old=button.innerHTML;button.innerHTML="…";button.disabled=true;try{const response=await fetch("https://generativelanguage.googleapis.com/v1beta/models/gemini-2.5-flash:generateContent",{method:"POST",headers:{"Content-Type":"application/json","x-goog-api-key":key},body:JSON.stringify({contents:[{parts:[{text:"Improve this UI snapshot for a coding assistant. Preserve every factual detail, replace cryptic control names with realistic user-facing names, group controls into meaningful sections, and add concise locator guidance. Do not invent controls. Return Markdown only.\n\n"+current()}]}]})});if(!response.ok)throw new Error();const data=await response.json();const text=data.candidates?.[0]?.content?.parts?.map(p=>p.text||"").join("").trim();if(text){$("format").value="markdown";$("preview").value=text;button.innerHTML="✓";button.title="Enhanced with Gemini";setTimeout(()=>{button.innerHTML=old},1600);}}catch{$("meta").textContent="Gemini enhancement failed";button.innerHTML=old;}finally{button.disabled=false;}});
