const VERSION = "contextlens.snapshot.v2.1";
const SENSITIVE_TYPES = new Set(["password", "hidden"]);
const INTERACTIVE = "a,button,input,select,textarea,summary,option,[contenteditable='true'],[role='button'],[role='link'],[role='checkbox'],[role='radio'],[role='switch'],[role='tab'],[role='menuitem'],[role='menuitemcheckbox'],[role='menuitemradio'],[role='combobox'],[role='option'],[role='listbox'],[role='gridcell'],[role='treeitem'],[role='spinbutton'],[role='slider'],[role='searchbox'],[role='textbox']";
const cleanText = (value, max = 240) => String(value || "").replace(/\s+/g, " ").trim().slice(0, max);
const humanize = value => cleanText(String(value || "").replace(/\d{5,}/g, "").replace(/([a-z])([A-Z])/g, "$1 $2").replace(/[\-_]+/g, " ").replace(/\b(ui|id|btn|lbl|txt|frm|div)\b/gi, "").replace(/\s+/g, " ").trim().replace(/\b\w/g, c => c.toUpperCase()), 120);
const generated = value => /(?:^|[_-])\d{3,}$/.test(String(value || "")) || /\d{8,}/.test(String(value || ""));
const isSensitive = el => SENSITIVE_TYPES.has((el.type || "").toLowerCase()) || el.autocomplete === "cc-number" || /pass(word)?|secret|token|ssn|credit.?card/i.test(`${el.name} ${el.id} ${el.getAttribute("aria-label") || ""}`);
const visible = el => { const r = el.getBoundingClientRect(); const s = getComputedStyle(el); return r.width > 0 && r.height > 0 && s.visibility !== "hidden" && s.display !== "none"; };
const nameOf = el => {
  const labelled = el.getAttribute("aria-label") || el.labels?.[0]?.innerText || el.getAttribute("title") || el.placeholder;
  const text = cleanText(el.innerText, 120);
  const raw = labelled || text || (el.tagName === "INPUT" ? humanize(el.name || el.id || el.type) : "");
  return humanize(raw) || `Unnamed ${el.tagName.toLowerCase()}`;
};
const roleOf = el => el.getAttribute("role") || ({BUTTON:"button",A:"link",INPUT:({checkbox:"checkbox",radio:"radio",range:"slider",search:"searchbox",number:"spinbutton"}[el.type] || "textbox"),SELECT:"combobox",TEXTAREA:"textbox",OPTION:"option"}[el.tagName] || undefined);
const attrs = el => Object.fromEntries(["id","name","type","role","href","placeholder","title","data-testid","aria-expanded","aria-checked","aria-selected","aria-invalid"].map(k => [k, el.getAttribute(k)]).filter(([,v]) => v !== null && !generated(v)));
const locatorHints = el => { const a = attrs(el), hints = [], n = nameOf(el), role = roleOf(el); const add=(type,value,priority,unique)=>hints.push({type,value,priority,unique}); if (a["data-testid"]) add("testid",`[data-testid="${a["data-testid"]}"]`,1,true); if (a.id && /^[A-Za-z][\w-]{2,50}$/.test(a.id) && !generated(a.id)) add("id",`#${CSS.escape(a.id)}`,2,document.querySelectorAll(`#${CSS.escape(a.id)}`).length===1); if (a.name && !generated(a.name)) add("name",`${el.tagName.toLowerCase()}[name="${a.name}"]`,3,document.querySelectorAll(`${el.tagName.toLowerCase()}[name="${CSS.escape(a.name)}"]`).length===1); if(role) { add("playwright",`getByRole("${role}", { name: "${n.replace(/"/g,"\\\"")}" })`,4,false); add("role",`role=${role} name="${n}"`,5,false); } return hints.slice(0, 6); };
const sectionContext = el => { const parent=el.closest("fieldset,section,article,form,[role=region],[role=tabpanel],[role=group]"); if(!parent) return undefined; const heading=parent.querySelector(":scope > legend,:scope > h1,:scope > h2,:scope > h3,:scope > h4,:scope > [role=heading]"); return humanize(parent.getAttribute("aria-label") || heading?.innerText || parent.getAttribute("name") || parent.id) || undefined; };
const node = el => ({tag: el.tagName.toLowerCase(), text: cleanText(el.innerText, 180), name: nameOf(el), role: roleOf(el), section: sectionContext(el), attributes: attrs(el), locatorHints: locatorHints(el)});
function interactive(root) { return [...root.querySelectorAll(INTERACTIVE)].filter(visible).map((el, i) => ({index: i + 1, ...node(el), value: isSensitive(el) ? "[REDACTED]" : cleanText(el.value, 120), state: {disabled: !!el.disabled || el.getAttribute("aria-disabled") === "true", checked: !!el.checked || el.getAttribute("aria-checked") === "true", selected: !!el.selected || el.getAttribute("aria-selected") === "true", expanded: el.getAttribute("aria-expanded"), invalid: el.getAttribute("aria-invalid") === "true" || !!el.closest("form")?.querySelector(":invalid")}})); }
function dialogs(root) { return [...root.querySelectorAll("dialog,[role=dialog],[role=alertdialog],[aria-modal=true]")].filter(visible).map(el => ({...node(el), heading: cleanText(el.querySelector("h1,h2,h3,[role=heading]")?.innerText), controls: interactive(el)})); }
function tableData(el) { return {caption:cleanText(el.querySelector("caption")?.innerText), headers:[...el.querySelectorAll("thead th,thead td")].map(x=>cleanText(x.innerText)).filter(Boolean), rows:[...el.querySelectorAll("tbody tr, tr")].slice(0,500).map((row,index)=>({index:index+1, cells:[...row.querySelectorAll(":scope > th,:scope > td")].map(cell=>({text:cleanText(cell.innerText,180), controls:interactive(cell).slice(0,30)})).filter(cell=>cell.text||cell.controls.length)})).filter(row=>row.cells.length)}; }
function sections(root) { const candidates=[...root.querySelectorAll("main,nav,header,aside,section,article,form,fieldset,table,[role=main],[role=region],[role=tabpanel],[role=group],[role=dialog],[role=grid],[role=tree]")].filter(visible); return candidates.map(el => { const heading=el.querySelector(":scope > h1,:scope > h2,:scope > h3,:scope > h4,:scope > h5,:scope > legend,:scope > [role=heading]"); const name=humanize(el.getAttribute("aria-label") || heading?.innerText || el.getAttribute("name") || el.id); const controls=interactive(el).slice(0, 2000); const text=cleanText(el.innerText, 1200); const item={tag:el.tagName.toLowerCase(), name:name || `${el.tagName.toLowerCase()} section`, heading:cleanText(heading?.innerText), text, attributes:attrs(el), controls, content: text ? text.split(/(?<=[.!?])\s+/).slice(0,30) : []}; if(el.tagName==="TABLE" || el.getAttribute("role")==="grid") item.table=tableData(el); return item; }).filter(x => x.controls.length || x.text).slice(0, 300); }
function frameSnapshots(root, path="top", depth=0) { if(depth>6) return []; return [...root.querySelectorAll("iframe,frame")].slice(0, 100).map((frame, i) => { const item={path:`${path} > iframe[${i}]`, name: frame.name || frame.title || undefined, src: frame.getAttribute("src") || undefined, accessible:false, sections:[], controls:[], childFrames:[]}; try { const doc=frame.contentDocument; if(doc){item.accessible=true;item.sections=sections(doc);item.controls=interactive(doc).slice(0,2000);item.childFrames=frameSnapshots(doc,item.path,depth+1);}} catch { item.reason="cross-origin frame; metadata only"; } return item; }); }
function extractSnapshot() { const allSections=sections(document); return {metadata: {url: location.href, title: document.title, origin: location.origin, capturedAt: new Date().toISOString(), viewport: {width: innerWidth, height: innerHeight}}, page: {heading: cleanText(document.querySelector("h1,h2,[role=heading]")?.innerText), hierarchy: allSections, sections: allSections, controls: interactive(document).slice(0, 5000), dialogs: dialogs(document), frames: frameSnapshots(document), validation: [...document.querySelectorAll(":invalid,[aria-invalid=true]")].filter(visible).slice(0, 500).map(el => ({...node(el), message: el.validationMessage}))}}; }
const buildSnapshot = (capture, sequence) => ({schema: VERSION, sequence, ...capture});
let snapshots = [];
function capture(){const s=buildSnapshot(extractSnapshot(),1);snapshots=[s];chrome.runtime.sendMessage({type:"SNAPSHOT_ADDED",snapshot:s,snapshots});}
chrome.runtime.onMessage.addListener((m, sender, sendResponse)=>{if(m.type==="CAPTURE"||m.type==="CAPTURE_V2"){capture();sendResponse({ok:true});} if(m.type==="CLEAR"){snapshots=[];sendResponse({ok:true});} return true;});
chrome.runtime.sendMessage({type:"CONTENT_READY"});
