const VERSION = "dom2ai.snapshot.v0.1";
const SENSITIVE_TYPES = new Set(["password", "hidden"]);
const INTERACTIVE = "a,button,input,select,textarea,[role='button'],[role='link'],[role='checkbox'],[role='radio'],[role='tab'],[role='menuitem'],[contenteditable='true'],summary";
const cleanText = (value, max = 240) => String(value || "").replace(/\s+/g, " ").trim().slice(0, max);
const humanize = value => cleanText(String(value || "").replace(/([a-z])([A-Z])/g, "$1 $2").replace(/[\-_]+/g, " ").replace(/\b(ui|id|btn|lbl|txt|frm|div)\b/gi, "").replace(/\s+/g, " ").trim().replace(/\b\w/g, c => c.toUpperCase()), 120);
const generated = value => /(?:^|[_-])\d{3,}$/.test(String(value || "")) || /\d{8,}/.test(String(value || ""));
const isSensitive = el => SENSITIVE_TYPES.has((el.type || "").toLowerCase()) || el.autocomplete === "cc-number" || /pass(word)?|secret|token|ssn|credit.?card/i.test(`${el.name} ${el.id} ${el.getAttribute("aria-label") || ""}`);
const visible = el => { const r = el.getBoundingClientRect(); const s = getComputedStyle(el); return r.width > 0 && r.height > 0 && s.visibility !== "hidden" && s.display !== "none"; };
const nameOf = el => {
  const labelled = el.getAttribute("aria-label") || el.labels?.[0]?.innerText || el.getAttribute("title") || el.placeholder;
  const text = cleanText(el.innerText, 120);
  const raw = labelled || text || (el.tagName === "INPUT" ? humanize(el.name || el.id || el.type) : "");
  return humanize(raw) || `Unnamed ${el.tagName.toLowerCase()}`;
};
const attrs = el => Object.fromEntries(["id","name","type","role","href","placeholder","title","data-testid","aria-expanded","aria-checked","aria-selected","aria-invalid"].map(k => [k, el.getAttribute(k)]).filter(([,v]) => v !== null && !generated(v)));
const locatorHints = el => { const a = attrs(el), hints = []; if (a["data-testid"]) hints.push({type:"testid", value:`[data-testid="${a["data-testid"]}"]`, priority:1}); if (a.id && /^[A-Za-z][\w-]{2,50}$/.test(a.id) && !generated(a.id)) hints.push({type:"id", value:`#${CSS.escape(a.id)}`, priority:2}); if (a.name && !generated(a.name)) hints.push({type:"name", value:`${el.tagName.toLowerCase()}[name="${a.name}"]`, priority:3}); const role=el.getAttribute("role") || ({BUTTON:"button",A:"link",INPUT:"textbox",SELECT:"combobox"}[el.tagName]); if(role) hints.push({type:"role", value:`role=${role} name="${nameOf(el)}"`, priority:4}); return hints.slice(0, 4); };
const node = el => ({tag: el.tagName.toLowerCase(), text: cleanText(el.innerText, 180), name: nameOf(el), role: el.getAttribute("role") || undefined, attributes: attrs(el), locatorHints: locatorHints(el)});
function interactive(root) { return [...root.querySelectorAll(INTERACTIVE)].filter(visible).map((el, i) => ({index: i + 1, ...node(el), value: isSensitive(el) ? "[REDACTED]" : cleanText(el.value, 120), state: {disabled: !!el.disabled, checked: !!el.checked, expanded: el.getAttribute("aria-expanded"), invalid: el.getAttribute("aria-invalid") === "true" || !!el.closest("form")?.querySelector(":invalid")}})); }
function dialogs(root) { return [...root.querySelectorAll("dialog,[role=dialog],[role=alertdialog],[aria-modal=true]")].filter(visible).map(el => ({...node(el), heading: cleanText(el.querySelector("h1,h2,h3,[role=heading]")?.innerText), controls: interactive(el)})); }
function sections(root) { const candidates=[...root.querySelectorAll("main,nav,header,aside,section,article,form,fieldset,table,[role=main],[role=region],[role=tabpanel],[role=group]")].filter(visible); return candidates.map(el => { const heading=el.querySelector(":scope > h1,:scope > h2,:scope > h3,:scope > h4,:scope > h5,:scope > legend,:scope > [role=heading]"); const name=humanize(el.getAttribute("aria-label") || heading?.innerText || el.getAttribute("name") || el.id); const controls=interactive(el).slice(0, 80); const text=cleanText(el.innerText, 420); return {tag:el.tagName.toLowerCase(), name:name || `${el.tagName.toLowerCase()} section`, heading:cleanText(heading?.innerText), text, attributes:attrs(el), controls, content: text ? text.split(/(?<=[.!?])\s+/).slice(0,12) : []}; }).filter(x => x.controls.length || x.text).slice(0, 100); }
function frameSnapshots(root, path="top") { return [...root.querySelectorAll("iframe,frame")].slice(0, 20).map((frame, i) => { const item={path:`${path} > iframe[${i}]`, name: frame.name || frame.title || undefined, src: frame.getAttribute("src") || undefined, accessible:false, sections:[], controls:[]}; try { const doc=frame.contentDocument; if(doc){item.accessible=true;item.sections=sections(doc);item.controls=interactive(doc).slice(0,80);}} catch { item.reason="cross-origin frame; metadata only"; } return item; }); }
function extractSnapshot() { const allSections=sections(document); return {metadata: {url: location.href, title: document.title, origin: location.origin, capturedAt: new Date().toISOString(), viewport: {width: innerWidth, height: innerHeight}}, page: {heading: cleanText(document.querySelector("h1")?.innerText), hierarchy: allSections, sections: allSections, controls: interactive(document).slice(0, 300), dialogs: dialogs(document), frames: frameSnapshots(document), validation: [...document.querySelectorAll(":invalid")].filter(visible).slice(0, 60).map(el => ({...node(el), message: el.validationMessage}))}}; }
const buildSnapshot = (capture, sequence) => ({schema: VERSION, sequence, ...capture});
let snapshots = [];
function capture(){const s=buildSnapshot(extractSnapshot(),1);snapshots=[s];chrome.runtime.sendMessage({type:"SNAPSHOT_ADDED",snapshot:s,snapshots});}
chrome.runtime.onMessage.addListener((m, sender, sendResponse)=>{if(m.type==="CAPTURE"){capture();sendResponse({ok:true});} if(m.type==="CLEAR"){snapshots=[];sendResponse({ok:true});} return true;});
chrome.runtime.sendMessage({type:"CONTENT_READY"});
