import { cleanText, isSensitive, INTERACTIVE } from "../shared/schema.js";

const visible = el => { const r = el.getBoundingClientRect(); const s = getComputedStyle(el); return r.width > 0 && r.height > 0 && s.visibility !== "hidden" && s.display !== "none"; };
const nameOf = el => cleanText(el.getAttribute("aria-label") || el.getAttribute("aria-labelledby") && [...el.ownerDocument.querySelectorAll(`#${CSS.escape(el.getAttribute("aria-labelledby"))}`)].map(x => x.innerText).join(" ") || el.labels?.[0]?.innerText || el.innerText || el.placeholder || el.title || el.value);
const attrs = el => Object.fromEntries(["id","name","type","role","href","placeholder","title","data-testid","aria-expanded","aria-checked","aria-selected","aria-invalid","autocomplete"].map(k => [k, el.getAttribute(k)]).filter(([,v]) => v !== null));
const locatorHints = el => { const a = attrs(el), hints = []; if (a["data-testid"]) hints.push(`[data-testid="${a["data-testid"]}"]`); if (a.id && /^[A-Za-z][\\w-]{2,50}$/.test(a.id)) hints.push(`#${CSS.escape(a.id)}`); if (a.name) hints.push(`${el.tagName.toLowerCase()}[name="${a.name}"]`); if (a.role && nameOf(el)) hints.push(`role=${a.role}[name="${nameOf(el).replace(/"/g,"\\\"")}"]`); return hints.slice(0, 4); };
const node = el => ({tag: el.tagName.toLowerCase(), text: cleanText(el.innerText, 180), name: nameOf(el), role: el.getAttribute("role") || undefined, attributes: attrs(el), locatorHints: locatorHints(el)});

function interactive(root) { return [...root.querySelectorAll(INTERACTIVE)].filter(visible).map((el, i) => ({index: i + 1, ...node(el), value: isSensitive(el) ? "[REDACTED]" : cleanText(el.value, 120), state: {disabled: !!el.disabled, checked: !!el.checked, expanded: el.getAttribute("aria-expanded"), invalid: el.getAttribute("aria-invalid") === "true" || !!el.closest("form")?.querySelector(":invalid")}})); }
function dialogs(root) { return [...root.querySelectorAll("dialog,[role=dialog],[role=alertdialog],[aria-modal=true]")].filter(visible).map(el => ({...node(el), heading: cleanText(el.querySelector("h1,h2,h3,[role=heading]")?.innerText), controls: interactive(el)})); }
function sections(root) { return [...root.querySelectorAll("main,header,nav,aside,section,form,article,[role=main],[role=region]")].filter(visible).slice(0, 30).map(el => ({tag: el.tagName.toLowerCase(), name: nameOf(el) || cleanText(el.querySelector("h1,h2,h3,h4")?.innerText), text: cleanText(el.innerText, 220), controls: interactive(el).slice(0, 30)})); }
function tables(root) { return [...root.querySelectorAll("table")].filter(visible).slice(0, 10).map(t => ({caption: cleanText(t.caption?.innerText), headers: [...t.querySelectorAll("th")].slice(0, 20).map(x => cleanText(x.innerText)), rows: [...t.querySelectorAll("tbody tr")].slice(0, 20).map(r => [...r.cells].map(c => cleanText(c.innerText, 100)))})); }
export function extractSnapshot() { const root = document; return {metadata: {url: location.href, title: document.title, origin: location.origin, capturedAt: new Date().toISOString(), viewport: {width: innerWidth, height: innerHeight}}, page: {heading: cleanText(document.querySelector("h1")?.innerText), landmarks: sections(root), controls: interactive(root).slice(0, 150), dialogs: dialogs(root), tables: tables(root), validation: [...root.querySelectorAll(":invalid")].filter(visible).slice(0, 30).map(el => ({...node(el), message: el.validationMessage}))}}; }
